### ISSUE TITLE
Producer terminate

### ISSUE THREAD

**Issue by FedericoPanS** [dashbitco/broadway_kafka#65]
Hello, I am new to Broadway. I am working with the Broadway Kafka producer and when I stopped the pipeline i realized that the brod processes remain running.
When I looked at the  Broadway.Topology.ProducerStage I see that it is not set to trap exits (unlike the Broadway.Topology.ProcessorStage) and so the GenServer terminate function is not called so the terminate in the KafkaBroadway.Producer never gets called either and no clean up is performed.
Please let me know if I am getting something wrong or this is indeed sort of a bug.

**Comment by FedericoPanS** [comment]
Thank you, I'll be happy to send a PR. Just to be sure, the way to go about it is to let each producer set the trap exit flag to true if they need to perform clean up in the terminate?
Also, is it possible to perform clean up in the processor? Right now I'm also sending to Kafka and would like to close the connection when the pipeline stops. 
Thanks!

**Comment by josevalim** [comment]
The fix is to call `Process.flag(:trap_exit, true)` in the producer init callback. That will set it for each producer.

Broadway shutdown is graceful, so all of the code in the processor, batchers, etc will push the remaning work before terminating. There is no additional clean up on processors and batch processors at the moment but we could support this feature in the Broadway topology if necessary (i.e. its own terminate callback).
